
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ChapterData : Luban.BeanBase
{
    public ChapterData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Image"].IsString) { throw new SerializationException(); }  Image = _buf["Image"]; }
    }

    public static ChapterData DeserializeChapterData(JSONNode _buf)
    {
        return new ChapterData(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly string Description;
    /// <summary>
    /// icon in chapter select
    /// </summary>
    public readonly string Image;
   
    public const int __ID__ = -2127193737;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "Image:" + Image + ","
        + "}";
    }
}

}
