
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ProductData : Luban.BeanBase
{
    public ProductData(JSONNode _buf) 
    {
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["BuildingId"].IsNumber) { throw new SerializationException(); }  BuildingId = _buf["BuildingId"]; }
        { if(!_buf["ResourceItemId"].IsNumber) { throw new SerializationException(); }  ResourceItemId = _buf["ResourceItemId"]; }
        { if(!_buf["ResourceAmount"].IsNumber) { throw new SerializationException(); }  ResourceAmount = _buf["ResourceAmount"]; }
        { if(!_buf["ProductItemId"].IsNumber) { throw new SerializationException(); }  ProductItemId = _buf["ProductItemId"]; }
        { if(!_buf["ProductAmount"].IsNumber) { throw new SerializationException(); }  ProductAmount = _buf["ProductAmount"]; }
        { if(!_buf["WorkLoad"].IsNumber) { throw new SerializationException(); }  WorkLoad = _buf["WorkLoad"]; }
        { if(!_buf["Score"].IsNumber) { throw new SerializationException(); }  Score = _buf["Score"]; }
        { if(!_buf["MaxWorkers"].IsNumber) { throw new SerializationException(); }  MaxWorkers = _buf["MaxWorkers"]; }
    }

    public static ProductData DeserializeProductData(JSONNode _buf)
    {
        return new ProductData(_buf);
    }

    public readonly string Name;
    public readonly int ID;
    public readonly string Description;
    public readonly int BuildingId;
    public readonly int ResourceItemId;
    public readonly int ResourceAmount;
    public readonly int ProductItemId;
    public readonly int ProductAmount;
    public readonly int WorkLoad;
    public readonly int Score;
    public readonly int MaxWorkers;
   
    public const int __ID__ = 175753497;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "ID:" + ID + ","
        + "Description:" + Description + ","
        + "BuildingId:" + BuildingId + ","
        + "ResourceItemId:" + ResourceItemId + ","
        + "ResourceAmount:" + ResourceAmount + ","
        + "ProductItemId:" + ProductItemId + ","
        + "ProductAmount:" + ProductAmount + ","
        + "WorkLoad:" + WorkLoad + ","
        + "Score:" + Score + ","
        + "MaxWorkers:" + MaxWorkers + ","
        + "}";
    }
}

}
