
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class CharacterName
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterNameData> _dataMap;
    private readonly System.Collections.Generic.List<CharacterNameData> _dataList;
    
    public CharacterName(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterNameData>();
        _dataList = new System.Collections.Generic.List<CharacterNameData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterNameData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CharacterNameData.DeserializeCharacterNameData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterNameData> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterNameData> DataList => _dataList;

    public CharacterNameData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterNameData Get(int key) => _dataMap[key];
    public CharacterNameData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

