
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class Product
{
    private readonly System.Collections.Generic.Dictionary<int, ProductData> _dataMap;
    private readonly System.Collections.Generic.List<ProductData> _dataList;
    
    public Product(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ProductData>();
        _dataList = new System.Collections.Generic.List<ProductData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ProductData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ProductData.DeserializeProductData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ProductData> DataMap => _dataMap;
    public System.Collections.Generic.List<ProductData> DataList => _dataList;

    public ProductData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ProductData Get(int key) => _dataMap[key];
    public ProductData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

