
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public SLG.TbConst TbConst {get; }
    public SLG.Item Item {get; }
    public SLG.TbDialogue TbDialogue {get; }
    public SLG.TbQuest TbQuest {get; }
    public SLG.TbAchi TbAchi {get; }
    public SLG.TbBuilding TbBuilding {get; }
    public SLG.TbChapter TbChapter {get; }
    public SLG.Product Product {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbConst = new SLG.TbConst(loader("slg_tbconst"));
        Item = new SLG.Item(loader("slg_item"));
        TbDialogue = new SLG.TbDialogue(loader("slg_tbdialogue"));
        TbQuest = new SLG.TbQuest(loader("slg_tbquest"));
        TbAchi = new SLG.TbAchi(loader("slg_tbachi"));
        TbBuilding = new SLG.TbBuilding(loader("slg_tbbuilding"));
        TbChapter = new SLG.TbChapter(loader("slg_tbchapter"));
        Product = new SLG.Product(loader("slg_product"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbConst.ResolveRef(this);
        Item.ResolveRef(this);
        TbDialogue.ResolveRef(this);
        TbQuest.ResolveRef(this);
        TbAchi.ResolveRef(this);
        TbBuilding.ResolveRef(this);
        TbChapter.ResolveRef(this);
        Product.ResolveRef(this);
    }
}

}
